### ISSUE TITLE
[PE-D][Tester E] Number too large causes 'budget' feature to be rendered unusable 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T18-4/tp#107]
When a value of 214748364821474836482147483648214748364821474836482147483648214748364821474836482147483648 is used. Budget becomes infinity. 
![Image 3-11-23 at 5.20 PM.jpg](https://raw.githubusercontent.com/ryanlohyr/ped/main/files/46bc7175-afc0-4a64-bf23-3bbda3771fa3.jpg)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: ryanlohyr/ped#4

**Comment by choonkit-nus** [comment]
Added a check to the parseBudget() method in Parser.java to ensure that the following conditions are met for the user entered amount. The budget amount is positive, less than 100000, and has at most two decimal places. This ensures that arbitrary large or small float amounts are rejected and not used. Hence, solving this issue.
