### ISSUE TITLE
[PE-D][Tester D] Size of list of transactions not accurate

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T18-4/tp#111]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
When i have 8 items and i delete 1, message says "15 items left"

![image.png](https://raw.githubusercontent.com/kaijie0102/ped/main/files/8ba13429-50dc-479c-ac75-54868d5d9922.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: kaijie0102/ped#9

**Comment by choonkit-nus** [comment]
This issue potentially resulted from an incorrect transactionList count where the count is not incremented when it reads in the transactions from the nuscents.txt file. Fixed the issue to ensure that when these transactions are loaded from the file, it increases the count too.
