### ISSUE TITLE
[PE-D][Tester E] States I have 8 items when only 7 are present 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-T18-4/tp#118]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
![Image 3-11-23 at 5.33 PM.jpg](https://raw.githubusercontent.com/ryanlohyr/ped/main/files/3dfb1f62-af72-4ed4-ba1a-f767aaaf2cc0.jpg)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ryanlohyr/ped#7

**Comment by spaceman03** [comment]
Duplicate issue
