### ISSUE TITLE
[PE-D][Tester C] Editing prints weird message

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T18-4/tp#123]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
After editing an entry, instead of printing a confirmation message, the list command is called without the user actually calling it.

![Screenshot 2023-11-03 at 17.36.39.png](https://raw.githubusercontent.com/danielpappa/ped/main/files/257f704a-1436-46f8-837a-70e93127588b.png)

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: danielpappa/ped#7

**Comment by spaceman03** [comment]
Perhaps we could print a confirmation message rather than the list message
