### ISSUE TITLE
[PE-D][Tester E] Conflicting user guide and CLI instructions 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-T18-4/tp#95]
![Image 3-11-23 at 5.03 PM.jpg](https://raw.githubusercontent.com/ryanlohyr/ped/main/files/264641e5-e1e5-43b9-b05c-7a6e3b89b43b.jpg)

![Image 3-11-23 at 5.03 PM.jpg](https://raw.githubusercontent.com/ryanlohyr/ped/main/files/7625d6e2-3431-4bc5-b90d-278a7015fe7d.jpg)

Categories supported in user guide includes rent, however rent is not supported in the application 

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: ryanlohyr/ped#3

**Comment by spaceman03** [comment]
Rent is a category for expense and not allowance, I suspect the user misunderstood it as an allowance category.
Perhaps we should update our UG to provide more details.
